### ISSUE TITLE
USER STORY: Account creation.

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#1]
# As a Site User, I want to register an account on the blog website so that I can create and manage my own posts.

## Acceptance Criteria

- AC1: User can access a form to register an account.
- AC2: User can create an account using their email and choose a password.
- AC2: Confirmation is given on successful account creation.

## Tasks

- [x] Install django-allauth
- [x] Stylise Log-in, Log-out and Sign Up pages.
- [x] Add Navbar links for Log-in, Log-out and Sign Up pages.

**Comment by 0davidog** [comment]
Link to account register form in navigation bar:

![Screenshot 2024-02-25 at 13-45-08 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/995d7927-fc02-4ea1-be2b-43634812fdfc)

Sign up form for user to register an account:

![Screenshot 2024-02-25 at 13-48-10 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/8abed4d8-2ba0-4c53-8c18-3fac3e0da7cb)

Fill required fields and hit submit button:

![Screenshot 2024-02-25 at 13-50-26 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/a3435a9e-e250-4c26-80de-ce15622fff29)

Confirmation message is given on return to home page:

![Screenshot 2024-02-25 at 13-50-43 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/ef51d79d-bdea-4df2-803f-bee694ce455d)
