### ISSUE TITLE
USER STORY: Create comment

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#12]
# As a Site User, I want to be able to comment on blog posts to engage with the author and other readers.

## Acceptance Criteria

- AC1: User (logged-in) has access to comment creation form.
- AC2: User is then able to fill required fields and submit comment.
- AC3: Confirmation given upon successful comment submission.

## Tasks

- [x] Create Comment Form.
- [x] Add comment form to full-report view.
- [x] Add comment form to full-report html.

**Comment by 0davidog** [comment]
User (logged-in) has access to comment creation form:

![Screenshot 2024-02-27 at 17-02-35 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/76f11c19-019c-4f03-ad4a-f16454e9de0d)

If user not logged in:

![Screenshot 2024-02-27 at 17-05-55 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/2bd2b015-a0d8-4ec0-a840-369d7afd765a)

Notice of successful comment submission:

![Screenshot 2024-02-27 at 17-07-49 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/59eb1c69-3cdc-46d0-9d09-f20077decb4a)

Comment listed awaiting approval:

![Screenshot 2024-02-27 at 17-08-32 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/0a150c9f-f04d-4271-9653-41b1b0b51879)

Comment listed approved:

![Screenshot 2024-02-27 at 17-13-33 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/858da771-6378-4fcb-994e-ebf4169e655d)

**Comment by 0davidog** [comment]
Trying to submit empty form:

![emptycomment](https://github.com/0davidog/Umbra-Report/assets/135815736/4c83bd8c-1b17-4f8c-b26e-9e09c137a401)
