### ISSUE TITLE
USER STORY: Like posts

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#14]
# As a Site User, I want to be able to like blog posts to engage with the author and other readers.

## Acceptance Criteria

- AC1: User (logged-in) has option/button to express approval on viewed post.
- AC2: Users 'like' can then be seen on post.

## Tasks

- [x] Add Like field to report model.
- [x] Add like button to full-report html.
- [x] Add like count display to full report html.

**Comment by 0davidog** [comment]
Like button and count on full report page:

![Screenshot 2024-02-27 at 17-33-18 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/7704fb05-610b-4300-b126-55e226cf84ef)

On click, like button becomes 'unlike' and count is increased by 1:

![Screenshot 2024-02-27 at 17-33-31 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/e4bfaf23-620c-4986-8dbe-ccccff8b0061)
