### ISSUE TITLE
USER STORY: Navigation menu

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#17]
# As a Site User, I want a user-friendly navigation menu that helps me explore different sections of the blog easily.

## Acceptance Criteria

- AC1: User has access to navigation bar/menu.
- AC2: Navigation menu is clear to understand.
- AC3: Selecting links takes user to expected site locations.

## Tasks

- [x]  Add navigation bar/menu to base.html.
- [x]  Wire up links.
- [x]  Test links.

**Comment by 0davidog** [comment]
The navigation menu is accessed by clicking the list icon:

![Screenshot 2024-02-27 at 16-49-29 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/3831c8b0-25ef-4434-9862-7bb9119db2da)

Navigation menu sidebar with links to home, about and user pages:

![Screenshot 2024-02-27 at 16-48-36 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/01c5132f-f2ae-4360-83c2-5842aadf30d8)

Links tested:

- [x] Clicking username takes user to user-page.
- [x] Clicking 'home' takes user to index page.
- [x] Clicking 'about' takes user to about page.
- [x] Clicking 'Login' takes user to login page.
- [x] Clicking 'Sign-Up' takes the user to signup page.
- [x] Clicking 'Logout' takes user to logout page.

**Comment by 0davidog** [comment]
This was updated to include Admin links (providing logged-in user is staff status):

![Screenshot 2024-03-03 at 18-04-22 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/fafd9b4f-831d-4df0-8b09-68bb37349a72)

Links tested:

- [x] Clicking 'Admin Home' takes the user to admin panel.
- [x] Clicking 'Report List' takes the user to admin panel report list.
- [x] Clicking 'Comment List' takes the user to admin panel comment list.
