### ISSUE TITLE
USER STORY: User log-in

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#2]
# As a Site User, I want to log in to the website securely using my credentials so that I can participate in the blog’s features.

## Acceptance Criteria

- AC1: User can access a form to log-in.
- AC2: User can then enter registered details to log-in.
- AC3: Confirmation is given upon successful log-in.
- AC4: Notice is given for unsuccessful log-in attempt.

## Tasks

- [x] Install django-allauth
- [x] Stylise log-in page.
- [x] Add navbar link to log-in page.
- [x] Add message function.

**Comment by 0davidog** [comment]
Link to Log-in form on navigation bar:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/d844dea5-cc4c-46d5-a313-44ce8a492410)

Log-in form:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/02b1792c-2544-44dc-b0f5-2201d7382571)

Enter details and hit submit:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/2c52f500-40ba-4e42-aa66-49922ba0d7af)

Confirmation message as user is returned to home page:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/6ac02b9a-4b1c-4c92-b1d6-a0a62f1ddb06)

**Comment by 0davidog** [comment]
Enter incorrect information:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/f245434b-40ab-47ba-8863-fd3ce6df6a22)

Message of unsuccessful log-in attempt:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/4c9e32b8-061d-41d3-b597-72b024e5e29e)
