### ISSUE TITLE
USER STORY: Read about page

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#20]
# As a Site User, I can click on the About link so that I can read about the site.

## Acceptance Criteria

- AC1: User has option/button to access about page.
- AC2: User is successfully taken to page.

## Tasks

- [x] Create About model.
- [x] Create About view.
- [x] Create About html.

**Comment by 0davidog** [comment]
The user can access About page through the navigation menu or by clicking the information icon next to the subheading:

![Screenshot 2024-02-27 at 17-16-38 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/e86ce2a5-8a6f-40b2-84c1-fadf413e7aaa)

The user is then taken to the about page:

![Screenshot 2024-02-27 at 17-18-56 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/a0bc8b20-1332-42e0-8245-8bf5f5aa2c8f)
