### ISSUE TITLE
USER STORY: Password reset

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#3]
# As a Site user, I want the option to reset my password in case I forget it, ensuring secure access to my account.

## Acceptance Criteria

- AC1: User can access a form for password reset.
- AC2: User can then enter details to perform a password reset.
- AC3: Confirmation is given for successful password reset.

## Tasks

- [x] install django-allauth
- [x] Add link to log-in page on navigation bar.
- [x] Style log-in page.
- [x] Check for link to password reset on log-in page.
- [x] Style password reset page.

**Comment by 0davidog** [comment]
Link to log-in page on navigation bar:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/c1d75eb0-c696-4dfb-a276-61959acdce06)

Link to password reset page on log-in page (Forgot password?):

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/6ebf6f21-a276-484d-8452-df33fda85bac)

Enter user email to reset password:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/3e13d696-067c-49b4-8f9a-5a6830f82e50)

Password reset email sent message:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/1981dafc-e541-4209-81f7-7c9a796d3231)

Password reset email received:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/4e517661-e9ca-4bb9-9392-272150325357)

Password reset form (form cannot be submitted with empty fields):

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/94261585-0f0a-454e-9e9f-986af163fc6e)

Password reset confirmation:

![Image](https://github.com/0davidog/Umbra-Report/assets/135815736/1033b941-aea3-4288-a841-9a26878eb574)
