### ISSUE TITLE
USER STORY: Update post

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#5]
# As a Site User, I want the ability to update my existing blog posts to update or improve the content over time.

## Acceptance Criteria

- AC1: User (logged-in) has option/button to edit posts of which they are the author.
- AC2: User can then re-access post creation form and resubmit edits.
- AC3: Confirmation given for successful submission.
- AC4: Notice given for unsuccessful attempt.  

## Tasks

- [x]  Create edit post button.
- [x]  Add edit report view.
- [x]  Add edit report.html
- [x]  Test function.

**Comment by 0davidog** [comment]
Edit Link on index page view:

![Screenshot 2024-02-27 at 12-19-10 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/743f1dd5-0255-4b04-beb6-5e82e29a989e)

Edit button on detail view:

![Screenshot 2024-02-27 at 12-19-43 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/18b26b7e-705d-4389-b3ca-a1fbce9236b6)

Edit form:

![Screenshot 2024-02-27 at 12-20-22 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/653cab0c-1712-4032-b3bd-2353633f15c4)

Add edits:

![Screenshot 2024-02-27 at 12-32-37 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/601eed67-507c-4632-8327-dd57a4cae39a)

Success (requires admin approval again):

![Screenshot 2024-02-27 at 12-45-59 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/1c5982b8-4ba8-4e0d-bea7-3dfb65558037)

Unsuccessful attempt:

![Screenshot 2024-02-27 at 12-47-10 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/0c6f3c61-b3b8-49fd-86fa-2719d0275804)
