### ISSUE TITLE
USER STORY: Delete post

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#6]
# As a Site User, I want to be able to delete my own blog posts if I decide to remove them from the website.

## Acceptance Criteria

- AC1: User (logged-in) has option/button to delete blog post of which they are the author.
- AC2: Once selected, user is then asked for confirmation.
- AC3: Confirmation given for successful deletion.

## Tasks

- [x]  Add delete button to blog post.
- [x]  Add delete post view.
- [x]  Add delete post confirmation modal.
- [x]  Add delete post javascript

**Comment by 0davidog** [comment]
User (logged-in) has option/button to delete blog post of which they are the author:
(only posts by 0davidog have delete links on index page)

![Screenshot 2024-02-27 at 13-32-21 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/47eeb258-7b5e-4165-b261-28fe984c31ab)

Delete button on detail view:

![Screenshot 2024-02-27 at 14-07-31 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/9f0704ba-9384-4ce2-a230-b3a26fc3b007)

Delete confirmation modal:

![Screenshot 2024-02-27 at 14-08-33 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/fae513c1-10b5-46e8-b994-6b4b66ee1ec1)

Confirmation message:

![Screenshot 2024-02-27 at 14-09-26 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/00499917-72a4-47f0-b152-48808dd8d54f)
