### ISSUE TITLE
USER STORY: Draft post

### ISSUE THREAD

**Issue by 0davidog** [0davidog/Umbra-Report#7]
# As a Site User or Admin, I can create draft posts so that I can finish writing the content later.

## Acceptance Criteria

- AC1: User (logged-in) has access to post creation form.
- AC2: User can select draft as option in form.
- AC3: Confirmation given on successful draft creation.
- AC4: Notice given on unsuccessful attempt.
- AC5: User has access to saved draft to choose to publish when desired.

## Tasks

- [x] Create post creation form
- [x] Create post creation html
- [x] Create post creation view
- [x] Create user page html.
- [x] Create user page view.

**Comment by 0davidog** [comment]
Logged-in user has post creation button on index page:

![Screenshot 2024-02-27 at 14-23-00 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/aac03a4f-9933-43c7-983d-1f3d345b29c9)

Draft is selectable on post creation form:

![Screenshot 2024-02-27 at 14-25-04 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/2a209050-1e00-4b25-9e85-2b2e8034fce5)

Confirmation of post creation:

![Screenshot 2024-02-27 at 14-26-27 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/709282a2-74ac-4bb7-9399-c5ff0293878e)

Unsuccessful attempt message:

![Screenshot 2024-02-27 at 14-59-50 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/6ff79c58-9bbd-4af9-acc6-7e5b344ef60c)

User can select username on navigation bar or anywhere else the username is written to access user page:

![Screenshot 2024-02-27 at 14-52-02 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/7c019abe-f3ec-458d-b18b-6bfb9d47d8fe)

User page displays list of user's posts, draft is indicated before creation date:

![Screenshot 2024-02-27 at 14-54-44 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/392035ca-02c1-4a91-bb97-9f69e9b30065)

User can select story to enter full page view and select edit to publish story:

![Screenshot 2024-02-27 at 14-57-37 The Umbra Report](https://github.com/0davidog/Umbra-Report/assets/135815736/5cae4c4b-7349-4fa7-8801-4b1d0055cd51)
